version: "3"

services:
  loki:
    image: grafana/loki:latest
    user: root:root
    container_name: loki
    restart: unless-stopped
    ports:
      - "127.0.0.1:3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    networks:
      - proxy
  promtail:
    image: grafana/promtail:latest
    restart: unless-stopped
    container_name: promtail
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml
      - ${VOLUMES}/traefik/access.log:/traefik/access.log
      - /run/log/journal:/run/log/journal
      - /var/log/journal:/var/log/journal
      - /etc/machine-id:/etc/machine-id
    command: -config.file=/etc/promtail/config.yml
    networks:
      - proxy

networks:
  proxy:
    external: true
