version: '3'

services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - GF_SERVER_NAME=grafana.${BASE_DOMAIN}
      - GF_SERVER_ROOT_URL=https://grafana.${BASE_DOMAIN}/
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST
      - GF_SMTP_USER
      - GF_SMTP_PASSWORD
      - GF_SMTP_FROM_ADDRESS=grafana@noreply.${BASE_DOMAIN}
      - GF_SMTP_FROM_NAME=Grafana
      - GF_AUTH_GENERIC_OAUTH_ENABLED=true
      - GF_AUTH_GENERIC_OAUTH_NAME=Authelia
      - GF_AUTH_GENERIC_OAUTH_CLIENT_ID
      - GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
      - GF_AUTH_GENERIC_OAUTH_SCOPES=openid profile email groups
      - GF_AUTH_GENERIC_OAUTH_EMPTY_SCOPES=false
      - GF_AUTH_GENERIC_OAUTH_AUTH_URL=https://a.${BASE_DOMAIN}/api/oidc/authorization
      - GF_AUTH_GENERIC_OAUTH_TOKEN_URL=https://a.${BASE_DOMAIN}/api/oidc/token
      - GF_AUTH_GENERIC_OAUTH_API_URL=https://a.${BASE_DOMAIN}/api/oidc/userinfo
      - GF_AUTH_GENERIC_OAUTH_LOGIN_ATTRIBUTE_PATH=preferred_username
      - GF_AUTH_GENERIC_OAUTH_GROUPS_ATTRIBUTE_PATH=groups
      - GF_AUTH_GENERIC_OAUTH_NAME_ATTRIBUTE_PATH=name
      - GF_AUTH_GENERIC_OAUTH_USE_PKCE=true
    volumes:
      - "${VOLUMES}/grafana:/var/lib/grafana"
    labels:
      - "traefik.enable=true"
      - 'traefik.http.routers.grafana.entryPoints=https'
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.http.routers.grafana.rule=Host(`grafana.${BASE_DOMAIN}`)"

networks:
  proxy:
    external: true
