version: "3.8"

services:
  enigmatica:
    container_name: enigmatica
    image: itzg/minecraft-server:java8
    environment:
      EULA: "true"
      TYPE: "FORGE"
      VERSION: "1.12.2"
      FORGE_VERSION: "14.23.5.2860"
      FORGE_INSTALLER: "forge-1.12.2-14.23.5.2860-installer.jar"
      MEMORY: "6G"
    ports:
      - "25565:25565"
    stdin_open: true
    tty: true
    restart: unless-stopped
    volumes:
      - ${VOLUMES}/enigmatica:/data
