version: "3"

services:
  telegraf:
    image: telegraf
    container_name: telegraf
    restart: unless-stopped
    user: root:998
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy

networks:
  proxy:
    external: true
