version: '3'

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: unless-stopped
    networks:
      - proxy
    # ports:
    #   - '127.0.0.1:8086:8086'
    volumes:
      - ${VOLUMES}/influxdb:/var/lib/influxdb2
    labels:
      - "traefik.enable=true"
      - 'traefik.http.routers.influxdb.entryPoints=https'
      - "traefik.http.services.influxdb.loadbalancer.server.port=8086"
      - "traefik.http.routers.influxdb.rule=Host(`influxdb.${BASE_DOMAIN}`)"

networks:
  proxy:
    external: true
