version: "3.9"

services:
  qbittorrent:
    container_name: qbittorrent
    image: hotio/qbittorrent
    restart: unless-stopped
    ports:
      - "8118:8118"
    environment:
      - PUID
      - PGID
      - UMASK
      - TZ
      - VPN_ENABLED=true
      - VPN_LAN_NETWORK=192.168.90.0/24
      - VPN_CONF=wg0
      - VPN_IP_CHECK_DELAY=5
      - VPN_IP_CHECK_EXIT=true
      - PRIVOXY_ENABLED=false
    volumes:
      - ${VOLUMES}/qbittorrent:/config
      - ./wg0.conf:/config/wireguard/wg0.conf
      - ${VOLUMES}/data:/data
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qbittorrent.entrypoints=https"
      - "traefik.http.services.qbittorrent.loadbalancer.server.port=8080"
      - "traefik.http.routers.qbittorrent.rule=Host(`qb.${BASE_DOMAIN}`)"
      - 'traefik.http.routers.qbittorrent.middlewares=authelia@file'

networks:
  proxy:
    external: true
