global:
  sendAnonymousUsage: false

api:
  dashboard: true
  debug: false

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"
    http:
      middlewares:
        - "compression@file"
      tls:
        certResolver: cloudflare
        domains:
          - main: ""
            sans:
              - "*."
    http3:
      advertisedPort: 443
  ssh:
    address: ":22"
serversTransport:
  insecureSkipVerify: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    network: "proxy"
    exposedByDefault: false
  file:
    filename: /config.yml

experimental:
  http3: true
  plugins:
    themepark:
      moduleName: "github.com/packruler/traefik-themepark"
      version: "v1.2.2"

accessLog:
  filePath: "/traefik/access.log"

metrics:
  influxDB2:
    address: http://influxdb:8086
    token: asd
    org: main
    bucket: traefik

certificatesResolvers:
  cloudflare:
    acme:
      email: foo@domain.com
      storage: acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
